### ISSUE TITLE
Error XML0023 Exception on get transaction Method

### ISSUE THREAD

**Issue by Eduardomoberti** [Metadrop/redsys-query-php#2]
When I try the example in the project with our Merchant info y get an XML0023, I saw in https://github.com/nicoSWD/redsys-errors/blob/master/errors.php#L169 that correspond with "La firma no es válida".

The code that I use is:

```
use RedsysConsultasPHP\Client\Client;

$url = 'https://sis-t.redsys.es:25443/apl02/services/SerClsWSConsulta';
$client = new Client($url, 'Introduce your merchant password');

$order = 'Introduce Ds_Order';
$terminal = 'Introduce Ds_terminal';
$merchant_code = 'Introduce your Ds_merchantCode';
$response = $client->getTransaction($order, $terminal, $merchant_code);

print_r($response);
```

**Comment by mistermoper** [comment]
In that example the $order, $terminal, and merchant code are not setup. It doesn't works because it needs that you add the real values from your environment.

**Comment by Eduardomoberti** [comment]
@mistermoper Sorry, I thing you did not understand, I copy the example that I am using to debug, but the merchant info is confidential so I could not describe here.

**Comment by Eduardomoberti** [comment]
Here is an example of how to generate a signature. We still investigating.
https://github.com/jgmullor/Devopensource_Redsys/blob/master/lib/Redsys/apiRedsys.php#L194
